- alias: Turn on the outside lights when the sun sets
  trigger:
      platform: sun
      event: sunset
  action:
    service: light.turn_on
    entity_id: group.outside_lights

- alias: Turn off the outside lights when the sun rises
  trigger:
      platform: sun
      event: sunrise
  action:
    service: light.turn_off
    entity_id: group.outside_lights
