- alias: Turn on the outside lights when the sun sets
  trigger:
      platform: sun
      event: sunset
  action:
    service: light.turn_on
    entity_id: group.outside_lights

- alias: Turn off the outside lights when the sun rises
  trigger:
      platform: sun
      event: sunrise
  action:
    service: light.turn_off
    entity_id: group.outside_lights

- alias: Turn on office heater
  trigger:
    platform: time
    at: '11:06:00'
  condition:
    condition: state
    entity_id: 'binary_sensor.workday_sensor'
    state: 'on'
  action:
    service: switch.turn_on
    entity_id: switch.office_wemo
