- id: '1593378236436'
  alias: Turn on some lights when the sun sets
  description: ''
  trigger:
  - event: sunset
    platform: sun
  condition: []
  action:
  - data:
      brightness: 175
      kelvin: 2000
    entity_id: light.tv_media_lights
    service: light.turn_on
  - data: {}
    entity_id: light.outside
    service: light.turn_on
- id: '1593406386687'
  alias: Notify Heather when washer turns off
  description: ''
  trigger:
  - entity_id: binary_sensor.washer_state
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      data:
        push:
          thread-id: washer-off
      message: The washer has finished
      title: Hoooly shit, Heather
    service: notify.mobile_app_heather_palmers_iphone
