- platform: ring
- platform: workday
  country: US
- platform: template
  sensors:
    awake:
      friendly_name: "Awake"
      value_template: >-
        {{ is_state('sun.sun', 'above_horizon')
           and ( is_state(states.binary_sensor.cool_breeze_occupancy, 'on') or
                 is_state(states.binary_sensor.justin_s_office_occupancy, 'on') or
                 is_state(states.binary_sensor.master_bedroom_occupancy, 'on') )
        }}
