- platform: ring
- platform: workday
  country: US
- platform: template
  sensors:
    home_occupied:
      friendly_name: "Home occupied"
      value_template: >-
        {{  is_state('binary_sensor.cool_breeze_occupancy', 'on') or
            is_state('binary_sensor.justin_s_office_occupancy', 'on') or
            is_state('binary_sensor.master_bedroom_occupancy', 'on') or
            is_state('binary_sensor.camden_s_room_occupancy', 'on')
        }}
    awake:
      friendly_name: "Awake"
      value_template: >-
        {{ is_state('sun.sun', 'above_horizon')
           and ( is_state('binary_sensor.cool_breeze_occupancy', 'on') or
                 is_state('binary_sensor.justin_s_office_occupancy', 'on') or
                 is_state('binary_sensor.master_bedroom_occupancy', 'on') )
        }}
    washer_status:
      friendly_name: "Washer status"
      value_template: >-
        {{ is_state('switch.washer_wemo_insight', 'on')
           and states('sensor.washer_power') | float > 0.5
        }}
