# - platform: ring
- platform: workday
  country: US
- platform: template
  sensors:
    # Lets say haloween "season" is between Oct 7 - Nov 7 for the purpose
    # of things like haloween lights, etc
    halloween_season:
      friendly_name: "Halloween season"
      value_template: >-
        {{ (10, 7) < (now().month, now().day) < (11, 7) }}
    # Lets say Christmas "season" is December.
    christmas_season:
      friendly_name: "Christmas season"
      value_template: "{{ now().month == 12 }}"
    home_occupied:
      friendly_name: "Home occupied"
      value_template: >-
        {{  is_state('binary_sensor.cool_breeze_occupancy', 'on') or
            is_state('binary_sensor.justin_s_office_occupancy', 'on') or
            is_state('binary_sensor.master_bedroom_occupancy', 'on') or
            is_state('binary_sensor.camden_s_room_occupancy', 'on')
        }}
    awake:
      friendly_name: "Awake"
      value_template: >-
        {{ is_state('sun.sun', 'above_horizon')
           and ( is_state('binary_sensor.cool_breeze_occupancy', 'on') or
                 is_state('binary_sensor.justin_s_office_occupancy', 'on') or
                 is_state('binary_sensor.master_bedroom_occupancy', 'on') )
        }}
    washer_status:
      friendly_name: "Washer status"
      value_template: >-
        {{ is_state('switch.washer_wemo_insight', 'on')
           and states('sensor.washer_power') | float > 0.5
        }}
      icon_template: mdi:washing-machine
    kitchen_heater_status:
      friendly_name: "Kitchen heater status"
      value_template: >-
        {{ is_state('switch.kitchen_wemo_insight', 'on')
           and is_state_attr('switch.kitchen_wemo_insight', 'state_detail', 'on')
        }}
      icon_template: >-
        {% if is_state('switch.kitchen_wemo_insight', 'on')
            and is_state_attr('switch.kitchen_wemo_insight', 'state_detail', 'on') %}
          mdi:radiator
        {% else %}
          mdi:radiator-disabled
        {% endif %}
