# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  customize: !include customize.yaml

# Text to speech
tts:
  - platform: google_translate

light: !include lights.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
binary_sensor: !include binary_sensors.yaml
sensor: !include_dir_merge_list sensors

weather:
  - platform: openweathermap
    api_key: !secret openweathermap_api_key
    mode: freedaily
    latitude: !secret home_lat
    longitude: !secret home_lon

notify:
  - name: all_devices
    platform: group
    services:
      - service: mobile_app_justin_palmers_iphone
      - service: mobile_app_heather_palmers_iphone

wemo:
  discovery: false
  static:
    - 192.168.1.10
    - 192.168.1.8
