# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

light: !include lights.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

weather:
  - platform: openweathermap
    api_key: !secret openweathermap_api_key
    mode: freedaily
    latitude: !secret home_lat
    longitude: !secret  home_lon
    
sensor:
  - platform: awair
    access_token: !secret awair_access_token
    devices:
      # Living Room
      - uuid: awair-r2_19522
      # Bedroom
      - uuid: awair-r2_18895
      # Office
      - uuid: awair-r2_19550
      # Camden
      - uuid: awair-r2_19632
