- platform: group
  name: Floor lamp
  entities:
    - light.floorlamp_1
    - light.floorlamp_2
- platform: group
  name: TV media lights
  entities:
    - light.hue_tv_right
    - light.hue_tv_left
- platform: group
  name: Dining room
  entities:
    - light.hue_dining_room_1
    - light.hue_dining_room_2
    - light.hue_dining_room_3
    - light.hue_dining_room_4
    - light.hue_dining_room_5
- platform: group
  name: Kitchen
  entities:
    - light.hue_kitchen_1
    - light.hue_kitchen_2
    - light.hue_kitchen_3
    - light.hue_kitchen_4
    - light.hue_kitchen_5
- platform: group
  name: Hallway
  entities:
    - light.hue_hallway_1
    - light.hue_hallway_2
    - light.hue_hallway_3
- platform: group
  name: Bedroom
  entities:
    - light.hue_bedroom_lamp_justin
    - light.hue_bedroom_lamp_heather
    - light.hue_bedroom_lightstrip
- platform: group
  name: Stairway
  entities:
    - light.hue_stairway_1
    - light.hue_stairway_2
    - light.hue_stairway_3
- platform: group
  name: Garage
  entities:
    - light.hue_garage_1
    - light.hue_garage_2
    - light.hue_garage_3
- platform: group
  name: Porch
  entities:
    - light.hue_porch_1c
    - light.hue_porch_2c
- platform: group
  name: Office
  entities:
    - light.hue_office_1c
    - light.hue_office_2
    - light.hue_office_3
    - light.hue_office_4
    - light.hue_office_5
- platform: group
  name: Guest bedroom
  entities:
    - light.hue_guest_bedroom_1
    - light.hue_guest_bedroom_2
- platform: group
  name: Upstairs hallway
  entities:
    - light.hue_upstairs_hallway_1
    - light.hue_upstairs_hallway_2
    - light.hue_upstairs_hallway_3
# Super groups
- platform: group
  name: Living room
  entities:
    - light.hue_living_room_fan_c
    - light.tv_media_lights
    - light.floor_lamp
- platform: group
  name: Downstairs
  entities:
    - light.living_room
    - light.dining_room
    - light.floor_lamp
    - light.kitchen
    - light.tv_media_lights
    - light.hallway
    - light.hue_sink
- platform: group
  name: Upstairs
  entities:
    - light.office
    - light.upstairs_hallway
    - light.gueest_bedroom
    - light.hue_toilet
    - light.hue_shower
- platform: group
  name: Backyard
  entities:
    - light.hue_backdoor
    - light.garage
- platform: group
  name: Outside
  entities:
    - light.backyard
    - light.porch
- platform: group
  name: Inside
  entities:
    - light.downstairs
    - light.upstairs
    - light.stairway
- platform: group
  name: All
  entities:
    - light.inside
    - light.outside
