- platform: switch
  name: Back fence lights
  entity_id: switch.back_fence_lights
- platform: group
  name: Floor lamp
  entities:
    - light.floorlamp_1
    - light.floorlamp_2
- platform: group
  name: TV media lights
  entities:
    - light.tv_right_1p
    - light.tv_left_1p
- platform: group
  name: Dining room
  entities:
    - light.diningroom_1
    - light.diningroom_2
    - light.diningroom_3
    - light.diningroom_4
    - light.diningroom_5
- platform: group
  name: Kitchen
  entities:
    - light.kitchen_1
    - light.kitchen_2
    - light.kitchen_3
    - light.kitchen_4
    - light.kitchen_5
    - light.sink_1
- platform: group
  name: Hallway
  entities:
    - light.hallway_1
    - light.hallway_2
    - light.hallway_3
- platform: group
  name: Bedroom
  entities:
    - light.bedroom_lamp_justin
    - light.bedroom_lamp_heather
    - light.bed_1ls
- platform: group
  name: Stairway
  entities:
    - light.stairway_1
    - light.stairway_2
    - light.stairway_3
- platform: group
  name: Garage
  entities:
    - light.garage_1
    - light.garage_2
    - light.garage_3
- platform: group
  name: Porch
  entities:
    - light.porch_1c
    - light.porch_2c
- platform: group
  name: Office
  entities:
    - light.office_1
    - light.office_2
    - light.office_3
    - light.office_4
    - light.office_5c
- platform: group
  name: Guest bedroom
  entities:
    - light.guest_bedroom_1
    - light.guest_bedroom_2
- platform: group
  name: Upstairs hallway
  entities:
    - light.upstairs_hallway_1
    - light.upstairs_hallway_2
    - light.upstairs_hallway_3
- platform: group
  name: Main bathroom
  entities:
    - light.toilet_1
    - light.shower_1
# Super groups
- platform: group
  name: Living room
  entities:
    - light.livingroom_ceilingfan_1c
    - light.tv_media_lights
    - light.floor_lamp
- platform: group
  name: Downstairs
  entities:
    - light.living_room
    - light.dining_room
    - light.floor_lamp
    - light.kitchen
    - light.tv_media_lights
    - light.hallway
    - light.sink_1
- platform: group
  name: Upstairs
  entities:
    - light.office
    - light.upstairs_hallway
    - light.guest_bedroom
    - light.main_bathroom
- platform: group
  name: Backyard
  entities:
    - light.backdoor_1c
    - light.garage
    - light.back_fence_lights
- platform: group
  name: Outside
  entities:
    - light.backyard
    - light.porch
- platform: group
  name: Inside
  entities:
    - light.downstairs
    - light.upstairs
    - light.stairway
- platform: group
  name: All
  entities:
    - light.inside
    - light.outside
