- platform: template
  sensors:
    living_room_climate:
      value_template: "{{ state_attr('climate.cool_breeze', 'current_temperature') }}"
      friendly_name: 'Living Room'
      unit_of_measurement: '°'
      device_class: motion
