- platform: yr
- platform: ring
- platform: template
  sensors:
    climate_living_room:
      friendly_name: "Living Room"
      unit_of_measurement: 'ยบ'
      value_template: "{{ states('sensor.cool_breeze_temperature') }}"
      icon_template: >-
        {% if is_state('binary_sensor.cool_breeze_occupancy', 'on') %}
          mdi:run-fast
        {% else %}
          mdi:account-off-outline
        {% endif %}
    climate_master_bedroom:
      friendly_name: "Bedroom"
      value_template: "{{ states('sensor.master_bedroom_temperature') }}"
      unit_of_measurement: 'ยบ'
      icon_template: >-
        {% if is_state('binary_sensor.master_bedroom_occupancy', 'on') %}
          mdi:run-fast
        {% else %}
          mdi:account-off-outline
        {% endif %}
    climate_office:
      friendly_name: "Office"
      value_template: "{{ states('sensor.justin_s_office_temperature') }}"
      unit_of_measurement: 'ยบ'
      icon_template: >-
        {% if is_state('binary_sensor.justin_s_office_occupancy', 'on') %}
          mdi:run-fast
        {% else %}
          mdi:account-off-outline
        {% endif %}
    climate_camdens_bedroom:
      friendly_name: "Camden's Bedroom"
      value_template: "{{ states('sensor.camden_s_room_temperature') }}"
      unit_of_measurement: 'ยบ'
      icon_template: >-
        {% if is_state('binary_sensor.camden_s_room_occupancy', 'on') %}
          mdi:run-fast
        {% else %}
          mdi:account-off-outline
        {% endif %}
