- platform: yr
- platform: awair
  access_token: !secret awair_access_token
  devices:
    - uuid: awair-r2_19522
#       name: Livingroom Awair
#     - uuid: awair-r2_18895
#       name: Bedroom Awair
#     - uuid: awair-r2_19550
#       name: Office Awair
# - platform: ring
- platform: template
  sensors:
    climate_living_room:
      friendly_name: "Living Room"
      unit_of_measurement: "ยบ"
      value_template: "{{ states('sensor.living_room_temperature') }}"
      icon_template: >-
        {% if is_state('binary_sensor.living_room_occupancy', 'on') %}
          mdi:run-fast
        {% else %}
          mdi:account-off-outline
        {% endif %}
    climate_main_bedroom:
      friendly_name: "Main Bedroom"
      value_template: "{{ states('sensor.main_bedroom_temperature') }}"
      unit_of_measurement: "ยบ"
      icon_template: >-
        {% if is_state('binary_sensor.main_bedroom_occupancy', 'on') %}
          mdi:run-fast
        {% else %}
          mdi:account-off-outline
        {% endif %}
    climate_office:
      friendly_name: "Office"
      value_template: "{{ states('sensor.office_temperature') }}"
      unit_of_measurement: "ยบ"
      icon_template: >-
        {% if is_state('binary_sensor.office_occupancy', 'on') %}
          mdi:run-fast
        {% else %}
          mdi:account-off-outline
        {% endif %}
    climate_guest_bedroom:
      friendly_name: "Guest Bedroom"
      value_template: "{{ states('sensor.guest_bedroom_temperature') }}"
      unit_of_measurement: "ยบ"
      icon_template: >-
        {% if is_state('binary_sensor.guest_bedroom_occupancy', 'on') %}
          mdi:run-fast
        {% else %}
          mdi:account-off-outline
        {% endif %}
    kitchen_heater_power:
      friendly_name: "Kitchen space heater power"
      value_template: '{{ states.switch.kitchen_wemo_insight.attributes["current_power_w"] }}'
      unit_of_measurement: "W"
    kitchen_heater_today_energy:
      friendly_name: "Kitchen space heater today's energy"
      value_template: '{{ states.switch.kitchen_wemo_insight.attributes["today_energy_kwh"] }}'
      unit_of_measurement: "kwH"
    washer_power:
      friendly_name: "Washer power"
      value_template: '{{ states.switch.washer_wemo_insight.attributes["current_power_w"] }}'
      unit_of_measurement: "W"
    washer_today_energy:
      friendly_name: "Washer today's energy"
      value_template: '{{ states.switch.washer_wemo_insight.attributes["today_energy_kwh"] }}'
      unit_of_measurement: "kwH"
    unifi_traffic_total:
      friendly_name: "Unifi Traffic"
      value_template: '{{ states.sensor.unifi_gateway_traffic.attributes["total_gb"] }}'
      unit_of_measurement: "GB"
    unifi_traffic_down:
      friendly_name: "Unifi Traffic Down"
      value_template: '{{ states.sensor.unifi_gateway_traffic.attributes["rx_gb"] }}'
      unit_of_measurement: "GB"
    unifi_traffic_up:
      friendly_name: "Unifi Traffic Up"
      value_template: '{{ states.sensor.unifi_gateway_traffic.attributes["tx_gb"] }}'
      unit_of_measurement: "GB"
- platform: feedparser
  name: Portland liquor licenses
  feed_url: "https://www.portlandoregon.gov/rss.cfm?c=69018"
- platform: unifigateway
  host: !secret unifi_host
  username: !secret unifi_username
  password: !secret unifi_password
- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /
    - type: disk_free
      arg: /
    - type: memory_free
    - type: memory_use_percent
    - type: load_1m
    - type: load_5m
    - type: load_15m
