resources:
  - url: /local/lovelace/mini-media-player-bundle.js?v=1.0.2
    type: module
  - url: /local/lovelace/list-card-custom.js?v=0
    type: js
  - url: /local/lovelace/vertical-stack-in-card.js?v=0.1.3
    type: js
  - url: /local/lovelace/interface.css?v=0
    type: css
title: Palmer Palace
views:
  - title: Home
    cards:
      # Lights
      - type: entities
        title: Lights
        show_header_toggle: false
        entities:
          - type: section
            label: Downstairs
          - light.living_room
          - light.dining_room
          - light.kitchen
          - light.media
          - light.playroom
          - light.hallway
          - light.stairway
          - light.sink
          - type: section
            label: Upstairs
          - light.bedroom_main
          - light.office
          - light.main_bathroom
          - light.upstairs_hallway
          - type: section
            label: Outside
          - light.back_door
          - light.garage
          - light.front_porch

      # - type: entities
      #   show_header_toggle: false
      #   entities:
      #     - type: weblink
      #       name: Unifi Controller Local
      #       url: https://192.168.1.8:8443
      #       icon: mdi:lan
      #     - type: weblink
      #       name: Unifi Cloud Controller
      #       url: https://unifi.ubnt.com/#/controllers/1/50
      #       icon: mdi:cloud-search
      #     - type: weblink
      #       name: Unifi Gateway
      #       url: https://192.168.1.1/#/manage/main
      #       icon: mdi:security-network
      - type: entities
        title: Home Modes
        show_header_toggle: false
        entities:
          - input_boolean.debug_mode

      # HVAC
      - type: entities
        title: Climate
        show_header_toggle: false
        entities:
          - entity: climate.living_room
            name: Home
          - type: divider
          - sensor.climate_living_room
          - sensor.climate_office
          - sensor.climate_main_bedroom
          - sensor.climate_guest_bedroom

      # Weather
      - type: weather-forecast
        entity: weather.dark_sky

      # Media and apple tv
      - type: entities
        title: Media
        show_header_toggle: false
        entities:
          - type: section
            label: Apple TV
          - type: custom:mini-media-player
            entity: media_player.living_room
            artwork: full-cover-fit
            group: true
            icon: mdi:apple
            name: Living Room
            hide:
              volume: true
              source: true
              power: true
          - type: section
            label: Sonos
          - type: "custom:mini-media-player"
            entity: media_player.sonos_living_room
            icon: mdi:speaker
            artwork: cover
            source: icon
            info: scroll
            group: true
            volume_stateless: true
            hide:
              power: true
              shuffle: false
              source: true
            sonos:
              show_group_count: true
              sync_volume: true
              entities:
                - entity_id: media_player.sonos_office
                  name: Office
                - entity_id: media_player.sonos_bedroom
                  name: Bedroom
          - type: "custom:mini-media-player"
            entity: media_player.sonos_office
            icon: mdi:speaker
            group: true
            artwork: cover
            volume_stateless: true
            hide:
              controls: true
              power: true
          - type: "custom:mini-media-player"
            entity: media_player.sonos_bedroom
            icon: mdi:speaker
            group: true
            artwork: cover
            volume_stateless: true
            hide:
              controls: true
              power: true

      - type: custom:vertical-stack-in-card
        title: Network Traffic
        cards:
          - type: history-graph
            hours_to_show: 3
            entities:
              - entity: sensor.unifi_traffic_down
          - type: history-graph
            hours_to_show: 3
            entities:
              - entity: sensor.unifi_traffic_up

  - title: Miscellaneous
    cards:
      - type: entities
        entities:
          - sun.sun
          - binary_sensor.workday_sensor
          - binary_sensor.awake
          - switch.office_wemo
          - binary_sensor.home_occupied
          - binary_sensor.office_occupancy
          - binary_sensor.main_bedroom_occupancy
          - binary_sensor.guest_bedroom_occupancy
          - binary_sensor.living_room_occupancy
          - switch.kitchen_wemo_insight
          - binary_sensor.washer_status
          - binary_sensor.kitchen_heater_status
      # Ring Videos
      # - type: horizontal-stack
      #   cards:
      #     - type: picture-glance
      #       title: Front Door
      #       entities:
      #         - binary_sensor.ring_front_door_motion
      #         - sensor.ring_front_door_last_activity
      #       camera_image: camera.front_door
      #     - type: picture-glance
      #       title: Garage
      #       entities:
      #         - binary_sensor.ring_garage_motion
      #         - sensor.ring_garage_last_activity
      #       camera_image: camera.garage
      # Sensor graphs
      - type: vertical-stack
        cards:
          - type: history-graph
            hours_to_show: 8
            entities:
              - entity: sensor.washer_power
                name: Washer
          - type: history-graph
            hours_to_show: 8
            entities:
              - entity: sensor.kitchen_heater_power
                name: Kitchen heater
      - type: "custom:list-card-custom"
        entity: sensor.portland_liquor_licenses
        title: Portland liquor licenses
        row_limit: 10
        columns:
          - title: Title
            field: title
            add_link: link
            style:
              - font-weight: bold !important
          - title: Published
            field: published
          - title: Address
            field: summary
            regex: ".+?\\s-"
