title: Home
views:
  - title: Home
    badges:
      - sensor.yr_symbol
    cards:
      - type: entities
        title: Lights
        show_header_toggle: false
        entities:
          - light.kitchen
          - light.back_door
          - light.bed
          - light.dining_room
          - light.sink
          - light.office
          - light.garage
          - light.front_porch
          - light.playroom
          - light.hallway
          - light.stairs
  - title: Downstairs
    badges:
      - sensor.yr_symbol
  - title: Music
    cards:
      - type: media-control
        entity: media_player.lounge_room
