resources:
  - url: /local/lovelace/mini-media-player-bundle.js?v=1.0.2
    type: module
  - url: /local/lovelace/compact-custom-header/compact-custom-header.js?v=0.0.1
    type: module
title: Palmer Palace
views:
  - !include views/home
  - !include views/downstairs
