resources:
  - url: /local/lovelace/mini-media-player-bundle.js?v=1.0.2
    type: module
  - url: /local/lovelace/compact-custom-header/compact-custom-header.js?v=0.0.1
    type: module
title: Palmer Palace
views:
  - title: Home
    cards:
      - type: horizontal-stack
        cards:
          - type: picture-glance
            title: Front Door
            entities:
              - binary_sensor.ring_front_door_motion
              - sensor.ring_front_door_last_activity
            camera_image: camera.front_door
          - type: picture-glance
            title: Garage
            entities:
              - binary_sensor.ring_garage_motion
              - sensor.ring_garage_last_activity
            camera_image: camera.garage

      - type: entities
        title: Climate
        show_header_toggle: false
        entities:
          - entity: climate.cool_breeze
            name: Home
          - type: divider
          - sensor.climate_living_room
          - sensor.climate_office
          - sensor.climate_master_bedroom
          - sensor.climate_camdens_bedroom

      - type: weather-forecast
        entity: weather.dark_sky
      - type: entities
        title: Media
        show_header_toggle: false
        entities:
          - type: section
            label: Apple TV
          - type: custom:mini-media-player
            entity: media_player.living_room
            artwork: full-cover-fit
            group: true
            sonos:
              sync_volume: true
              entities:
                - media_player.sonos_living_room
          - type: section
            label: Sonos
          - type: "custom:mini-media-player"
            entity: media_player.sonos_living_room
            icon: mdi:speaker
            artwork: cover
            source: icon
            info: scroll
            group: true
            hide:
              power: true
              shuffle: false
            sonos:
              show_group_count: true
              sync_volume: true
              entities:
              - entity_id: media_player.sonos_office
                name: Office
              - entity_id: media_player.sonos_bedroom
                name: Bedroom
          - type: "custom:mini-media-player"
            entity: media_player.sonos_office
            icon: mdi:speaker
            group: true
            artwork: cover
            volume_stateless: true
            hide:
              controls: true
              power: true
          - type: "custom:mini-media-player"
            entity: media_player.sonos_bedroom
            icon: mdi:speaker
            group: true
            artwork: cover
            volume_stateless: true
            hide:
              controls: true
              power: true

      - type: entities
        title: Lights
        show_header_toggle: false
        entities:
          - type: section
            label: Downstairs
          - light.dining_room
          - light.kitchen
          - light.playroom
          - light.hallway
          - light.stairway
          - light.sink
          - type: section
            label: Upstairs
          - light.bed
          - light.office
          - type: section
            label: Outside
          - light.back_door
          - light.garage
          - light.front_porch

  # Downstairs section
  - title: Downstairs
    cards:
      - type: "custom:mini-media-player"
        entity: media_player.sonos_living_room
        icon: mdi:speaker
        artwork: full-cover
        source: icon
        info: short
        hide:
          power: true
          shuffle: false
        sonos:
          show_group_count: true
          sync_volume: true
          entities:
          - entity_id: media_player.sonos_office
            name: Office
          - entity_id: media_player.sonos_bedroom
            name: Bedroom
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: light
                entity: light.dining_room
              - type: light
                entity: light.kitchen
          - type: horizontal-stack
            cards:
              - type: light
                entity: light.hallway
              - type: light
                entity: light.stairway
