resources:
  - url: /local/lovelace/mini-media-player-bundle.js?v=1.0.2
    type: module
  - url: /local/lovelace/compact-custom-header/compact-custom-header.js?v=0.0.1
    type: module
title: Palmer Palace
views:
  - title: Home
    cards:
      - type: entities
        title: Climate
        show_header_toggle: false
        entities:
          - entity: climate.cool_breeze
            name: Home
          - type: divider
          - sensor.climate_living_room
          - sensor.climate_office
          - sensor.climate_master_bedroom
          - sensor.climate_camdens_bedroom
          # - entity: sensor.cool_breeze_temperature
          # - entity: sensor.camden_s_room_temperature
          # - entity: sensor.master_bedroom_temperature
          # - entity: sensor.justin_s_office_temperature
          # - entity: sensor.climate_living_room
          # - weather.cool_breeze
          # - climate.cool_breeze
          # - sensor.cool_breeze_humidity
          # - sensor.cool_breeze_temperature
          # - binary_sensor.cool_breeze_occupancy
          # - binary_sensor.camden_s_room_occupancy
          # - sensor.camden_s_room_temperature
          # - binary_sensor.justin_s_office_occupancy
          # - sensor.justin_s_office_temperature
          # - binary_sensor.master_bedroom_occupancy
          # - sensor.master_bedroom_temperature
      - type: weather-forecast
        entity: weather.dark_sky
      - type: history-graph
        hours_to_show: 12
        entities:
          - entity: climate.cool_breeze
            name: Living Room
      - type: entities
        title: Sonos
        show_header_toggle: false
        entities:
        - type: "custom:mini-media-player"
          entity: media_player.sonos_living_room
          icon: mdi:speaker
          artwork: cover
          source: icon
          info: scroll
          group: true
          hide:
            power: true
            shuffle: false
          sonos:
            show_group_count: true
            sync_volume: true
            entities:
            - entity_id: media_player.sonos_office
              name: Office
            - entity_id: media_player.sonos_bedroom
              name: Bedroom
        - type: "custom:mini-media-player"
          entity: media_player.sonos_office
          icon: mdi:speaker
          group: true
          artwork: cover
          hide:
            controls: true
            power: true
        - type: "custom:mini-media-player"
          entity: media_player.sonos_bedroom
          icon: mdi:speaker
          group: true
          artwork: cover
          hide:
            controls: true
            power: true
      - type: entities
        title: Lights
        show_header_toggle: false
        entities:
          - type: section
            label: Downstairs
          - light.dining_room
          - light.kitchen
          - light.playroom
          - light.hallway
          - light.stairs
          - light.sink
          - type: section
            label: Upstairs
          - light.bed
          - light.office
          - type: section
            label: Outside
          - light.back_door
          - light.garage
          - light.front_porch
  - title: Downstairs
    cards:
      - type: "custom:mini-media-player"
        entity: media_player.sonos_living_room
        icon: mdi:speaker
        artwork: full-cover
        source: icon
        info: short
        hide:
          power: true
          shuffle: false
        sonos:
          show_group_count: true
          sync_volume: true
          entities:
          - entity_id: media_player.sonos_office
            name: Office
          - entity_id: media_player.sonos_bedroom
            name: Bedroom
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: light
                entity: light.dining_room
              - type: light
                entity: light.kitchen
          - type: horizontal-stack
            cards:
              - type: light
                entity: light.hallway
              - type: light
                entity: light.stairs
