resources:
  - url: /local/lovelace/mini-media-player-bundle.js?v=1.0.2
    type: module
  - url: /local/lovelace/list-card-custom.js?v=0
    type: js
  - url: /local/lovelace/vertical-stack-in-card.js?v=0.1.3
    type: js
  - url: /local/lovelace/card-mod.js
    type: module
title: Palmer Palace
styles: &styles
  style: |
    ha-card {
      border-radius: 6px;
      box-shadow: 0 0 1px rgba(0, 0, 0, 0.4);
    }

    .card-header {
      font-size: 16px;
      padding: 12px;
      font-weight: bold;
      color: #333;
      line-height: 1em;
      border-bottom: 1px solid #eee;
    }
views:
  !include_dir_list views
  # - title: Miscellaneous
  #   cards:
  #     - type: entities
  #       <<: *styles
  #       entities:
  #         - sun.sun
  #         - binary_sensor.workday_sensor
  #         - binary_sensor.awake
  #         - binary_sensor.washer_status
  #         - binary_sensor.home_occupied
  #         - binary_sensor.office_occupancy
  #         - binary_sensor.main_bedroom_occupancy
  #         - binary_sensor.guest_bedroom_occupancy
  #         - binary_sensor.living_room_occupancy
  #         - binary_sensor.kitchen_heater_status
  #     - type: vertical-stack
  #       cards:
  #         - type: history-graph
  #           hours_to_show: 8
  #           entities:
  #             - entity: sensor.washer_power
  #               name: Washer
  #         - type: history-graph
  #           hours_to_show: 8
  #           entities:
  #             - entity: sensor.kitchen_heater_power
  #               name: Kitchen heater
  #     - type: "custom:list-card-custom"
  #       entity: sensor.portland_liquor_licenses
  #       title: Portland liquor licenses
  #       row_limit: 10
  #       columns:
  #         - title: Title
  #           field: title
  #           add_link: link
  #           style:
  #             - font-weight: bold !important
  #         - title: Published
  #           field: published
  #         - title: Address
  #           field: summary
  #           regex: ".+?\\s-"
