resources:
  - url: /local/lovelace/mini-media-player-bundle.js?v=1.0.2
    type: module
  - url: /local/lovelace/compact-custom-header/compact-custom-header.js?v=0.0.1
    type: module
  - url: /local/lovelace/list-card-custom.js?v=0
    type: js
title: Palmer Palace
views:
  ##     ##  #######  ##     ## ########
  ##     ## ##     ## ###   ### ##
  ##     ## ##     ## #### #### ##
  ######### ##     ## ## ### ## ######
  ##     ## ##     ## ##     ## ##
  ##     ## ##     ## ##     ## ##
  ##     ##  #######  ##     ## ########
  - title: Home
    cards:
      # Ring Videos
      - type: horizontal-stack
        cards:
          - type: picture-glance
            title: Front Door
            entities:
              - binary_sensor.ring_front_door_motion
              - sensor.ring_front_door_last_activity
            camera_image: camera.front_door
          - type: picture-glance
            title: Garage
            entities:
              - binary_sensor.ring_garage_motion
              - sensor.ring_garage_last_activity
            camera_image: camera.garage

      # HVAC
      - type: entities
        title: Climate
        show_header_toggle: false
        entities:
          - entity: climate.cool_breeze
            name: Home
          - type: divider
          - sensor.climate_living_room
          - sensor.climate_office
          - sensor.climate_primary_bedroom
          - sensor.climate_camdens_bedroom

      # Weather
      - type: weather-forecast
        entity: weather.dark_sky

      # Media and apple tv
      - type: entities
        title: Media
        show_header_toggle: false
        entities:
          - type: section
            label: Apple TV
          - type: custom:mini-media-player
            entity: media_player.living_room
            artwork: full-cover-fit
            group: true
            icon: mdi:apple
            name: Living Room
            hide:
              volume: true
              source: true
              power: true
          - type: section
            label: Sonos
          - type: "custom:mini-media-player"
            entity: media_player.sonos_living_room
            icon: mdi:speaker
            artwork: cover
            source: icon
            info: scroll
            group: true
            volume_stateless: true
            hide:
              power: true
              shuffle: false
              source: true
            sonos:
              show_group_count: true
              sync_volume: true
              entities:
              - entity_id: media_player.sonos_office
                name: Office
              - entity_id: media_player.sonos_bedroom
                name: Bedroom
          - type: "custom:mini-media-player"
            entity: media_player.sonos_office
            icon: mdi:speaker
            group: true
            artwork: cover
            volume_stateless: true
            hide:
              controls: true
              power: true
          - type: "custom:mini-media-player"
            entity: media_player.sonos_bedroom
            icon: mdi:speaker
            group: true
            artwork: cover
            volume_stateless: true
            hide:
              controls: true
              power: true

      # Lights
      - type: entities
        title: Lights
        show_header_toggle: false
        entities:
          - type: section
            label: Downstairs
          - light.living_room
          - light.dining_room
          - light.kitchen
          - light.playroom
          - light.hallway
          - light.stairway
          - light.sink
          - type: section
            label: Upstairs
          - light.bed
          - light.office
          - type: section
            label: Outside
          - light.back_door
          - light.garage
          - light.front_porch


##     ## ####  ######   ######  ######## ##       ##          ###    ##    ## ########  #######  ##     ##  ######
###   ###  ##  ##    ## ##    ## ##       ##       ##         ## ##   ###   ## ##       ##     ## ##     ## ##    ##
#### ####  ##  ##       ##       ##       ##       ##        ##   ##  ####  ## ##       ##     ## ##     ## ##
## ### ##  ##   ######  ##       ######   ##       ##       ##     ## ## ## ## ######   ##     ## ##     ##  ######
##     ##  ##        ## ##       ##       ##       ##       ######### ##  #### ##       ##     ## ##     ##       ##
##     ##  ##  ##    ## ##    ## ##       ##       ##       ##     ## ##   ### ##       ##     ## ##     ## ##    ##
##     ## ####  ######   ######  ######## ######## ######## ##     ## ##    ## ########  #######   #######   ######

  - title: Miscellaneous
    cards:
      - type: vertical-stack
        cards:
          - type: history-graph
            entities:
              - entity: sensor.washer_power
                name: Washer
          - type: history-graph
            entities:
              - entity: sensor.kitchen_heater_power
                name: Kitchen heater
      - type: entities
        entities:
          - sun.sun
          - binary_sensor.workday_sensor
          - binary_sensor.awake
          - switch.office_wemo
          - binary_sensor.home_occupied
          - binary_sensor.justin_s_office_occupancy
          - binary_sensor.master_bedroom_occupancy
          - binary_sensor.camden_s_room_occupancy
          - binary_sensor.cool_breeze_occupancy
          - switch.kitchen_wemo_insight
          - binary_sensor.washer_status
          - binary_sensor.kitchen_heater_status
      - type: glance
        title: Lights
        entities:
          - light.living_room
          - light.dining_room
          - light.kitchen
          - light.sink
          - light.hallway
          - light.stairway
          - light.office
          - light.bed
          - light.garage
          - light.back_door
          - light.front_porch
      - type: "custom:list-card-custom"
        entity: sensor.portland_liquor_licenses
        title: Portland liquor licenses
        row_limit: 6
        columns:
          - title: Title
            field: title
            add_link: link
            style:
              - white-space: nowrap
              - font-weight: bold !important
          - title: Published
            field: published
          - title: Address
            field: summary
            regex: ".+?\\s-"
            style:
              - text-transform: lowercase !important
