resources:
  - url: /local/lovelace/mini-media-player-bundle.js?v=1.0.2
    type: module
  - url: /local/lovelace/compact-custom-header/compact-custom-header.js?v=0.0.1
    type: module
title: Palmer Palace
views:
  - title: Home
    badges:
      - sensor.yr_symbol
    cards:
      - type: entities
        entities:
        - type: "custom:mini-media-player"
          entity: media_player.sonos_living_room
          artwork: cover
          source: icon
          info: short
          hide:
            volume: true
            power: true
        - type: "custom:mini-media-player"
          entity: media_player.sonos_office
          group: true
          artwork: cover
          source: icon
          hide:
            controls: true
        - type: "custom:mini-media-player"
          entity: media_player.sonos_bedroom
          group: true
          artwork: cover
          hide:
            controls: true
      - type: entities
        title: Lights
        show_header_toggle: false
        entities:
          - light.kitchen
          - light.back_door
          - light.bed
          - light.dining_room
          - light.sink
          - light.office
          - light.garage
          - light.front_porch
          - light.playroom
          - light.hallway
          - light.stairs
  - title: Downstairs
    badges:
      - sensor.yr_symbol
  - title: Music
    cards:
      - type: "custom:mini-media-player"
        entity: media_player.sonos_living_room
        icon: mdi:speaker
        more_info: true
        volume_stateless: true
        artwork: full-cover
      - type: "custom:mini-media-player"
        entity: media_player.sonos_office
        icon: mdi:speaker
        more_info: true
        volume_stateless: true
        artwork: full-cover
      - type: "custom:mini-media-player"
        entity: media_player.sonos_bedroom
        icon: mdi:speaker
        more_info: true
        volume_stateless: true
        artwork: full-cover
