- alias: A monitored light or light group turned on
  trigger:
    platform: state
    entity_id:
      - light.front_porch
    to: "on"
  condition:
    - condition: state
      entity_id: input_boolean.debug_mode
      state: "on"
  action:
    service: notify.mobile_app_justin_palmers_iphone
    data_template:
      title: "A light turned on"
      message: "{{ trigger.to_state.attributes.friendly_name }} turned on"
- alias: A monitored light or light group turned off
  trigger:
    platform: state
    entity_id:
      - light.front_porch_right
      - light.front_porch_left
      - light.front_porch
    to: "off"
  condition:
    - condition: state
      entity_id: input_boolean.debug_mode
      state: "on"
  action:
    service: notify.mobile_app_justin_palmers_iphone
    data_template:
      title: "A light turned off"
      message: "{{ trigger.to_state.attributes.friendly_name }} turned off"
