- alias: A monitored light come on
  trigger:
    platform: state
    entity_id:
      - light.h1
      - light.h2
      - light.h3
    to: "on"
  condition:
    - condition: state
      entity_id: input_boolean.debug_mode
      state: "on"
  action:
    service: notify.mobile_app_justin_palmers_iphone
    data_template:
      title: "A light turned on"
      message: "The light {{ trigger.to_state.attributes.friendly_name }} turned on yo"
# - alias: Notify Justin's Phone when left front porch light comes on
#   trigger:
#     platform: state
#     entity_id: light.fpc2
#     to: "on"
#   condition:
#     - condition: state
#       entity_id: input_boolean.debug_mode
#       state: "on"
#   action:
#     service: notify.ios_justin_palmers_iphone
#     data:
#       title: "Front porch - left light on"
#       message: "its on"
