- alias: Notify Justin's Phone when front porch lights comes on
  trigger:
    platform: state
    entities:
      - light.fpc1
      - light.fpc2
    to: "on"
  condition:
    - condition: state
      entity_id: input_boolean.debug_mode
      state: "on"
  action:
    service: notify.mobile_app_justin_palmers_iphone
    data:
      title: "A light turned on"
    data_template:
      message: "The {{ trigger.to_state.attributes.friendly_name }} turned on"
# - alias: Notify Justin's Phone when left front porch light comes on
#   trigger:
#     platform: state
#     entity_id: light.fpc2
#     to: "on"
#   condition:
#     - condition: state
#       entity_id: input_boolean.debug_mode
#       state: "on"
#   action:
#     service: notify.ios_justin_palmers_iphone
#     data:
#       title: "Front porch - left light on"
#       message: "its on"
