- alias: Notify Justin's phone when a new liquor license is issued in Portland
  trigger:
    platform: event
    event_type: feedreader
  action:
    service: notify.ios_justins_iphone
    data:
      title: "New liquor license issued at {{ trigger.event.data.title }}"
      message: "Location: don't know yet"
