- alias: Turn on office heater on workdays when we wake up
  trigger:
    platform: state
    entity_id: binary_sensor.awake
    to: "on"
  condition:
    - condition: state
      entity_id: binary_sensor.workday_sensor
      state: "on"
  action:
    service: switch.turn_on
    entity_id: switch.office_wemo

- alias: Turn off office heater when office is unoccupied for an hour
  trigger:
    platform: state
    entity_id: binary_sensor.justin_s_office_occupancy
    to: "off"
    for:
      hours: 1
  action:
    service: switch.turn_off
    entity_id: switch.office_wemo
# - alias: Turn off office heater when temp in office stays above 73
#   trigger:
#     platform: numeric_state
#     entity_id: sensor.justin_s_office_temperature
#     above: 73
#     for:
#       minutes: 15
#   action:
#     service: switch.turn_off
#     entity_id: switch.office_wemo
