- alias: Turn on the outside lights when the sun sets
  trigger:
    platform: sun
    event: sunset
  action:
    service: light.turn_on
    entity_id: group.outside_lights

- alias: Turn off the outside lights when the sun rises
  trigger:
    platform: sun
    event: sunrise
  action:
    service: light.turn_off
    entity_id: group.outside_lights

- alias: Turn on the media lights after the sun sets
  trigger:
    platform: sun
    event: sunset
  condition:
    - condition: state
      entity_id: input_boolean.guest_mode
      state: "off"
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: "off"
  action:
    service: light.turn_on
    entity_id: light.media
    data:
      brightness: 175
      kelvin: 2000
