- alias: Turn on the outside lights when the sun sets
  trigger:
    platform: sun
    event: sunset
  action:
    service: light.turn_on
    entity_id: group.outside_lights

- alias: Turn off the outside lights when the sun rises
  trigger:
    platform: sun
    event: sunrise
  action:
    service: light.turn_off
    entity_id: group.outside_lights

- alias: Set Front Porch lights to Halloween during season
  trigger:
    platform: state
    entity_id: light.media
    to: "on"
  condition:
    condition: state
    entity_id: binary_sensor.halloween_season
    state: "on"
  action:
    service: notify.ios_justins_iphone
    data:
      title: "Halloween"
      message: "The lights are on"

- alias: Turn on the media lights after the sun sets
  trigger:
    platform: sun
    event: sunset
  condition:
    - condition: state
      entity_id: input_boolean.guest_mode
      state: "off"
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: "off"
  action:
    service: light.turn_on
    entity_id: light.media
    data:
      brightness: 175
      kelvin: 2000
