- alias: "Notify if Unifi Firmware Update Available"
  initial_state: true
  trigger:
    - platform: template
      value_template: "{{ states(' sensor.unifi_gateway_firmware_upgradable') > '0' }}"
  condition:
    - condition: template
      value_template: "{{ trigger.from_state.state != 'None' }}"
    - condition: template
      value_template: "{{ trigger.from_state.state != 'unavailable' }}"
    - condition: template
      value_template: "{{ trigger.from_state.state > 0 }}"
  action:
    service: notify.mobile_app_justin_palmers_iphone
    data_template:
      title: "Unifi Network Device Firmware Update Available"
      message: "Unifi Network Device Firmware Update Available"
