name: verify-home-assistant-config

on:
  push:
    branches-ignore:
      - "main"
  schedule:
    - cron: 0 12 * * *

jobs:
  lint:
    # Name the Job
    name: Lint Code Base
    # Set the agent to run on
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v2

      ################################
      # Run Linter against code base #
      ################################
      - name: Lint Code Base
        uses: docker://github/super-linter:v2.2.0
        env:
          DEFAULT_BRANCH: main
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_YAML: true
  validate_config:
    name: Validate Homeassistant config
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Getting your configuration from GitHub
        uses: actions/checkout@v2
      - name: Copy secrets into configuration folder
        run: cp secrets.test.yaml secrets.yaml
      - name: Home Assistant Check
        uses: "docker://homeassistant/home-assistant:stable"
        with:
          args: python -m homeassistant --config . --script check_config --info all
