---
name: Verify Home Assistant configuration

# yamllint disable-line rule:truthy
on:
  push:
  pull_request:
  schedule:
    - cron: 0 12 * * *

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - name: Getting your configuration from GitHub
        uses: actions/checkout@v1
      - name: Running YAMLlint
        uses: "docker://pipelinecomponents/yamllint:latest"
        with:
          args: yamllint .
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Run the config check
#         uses: docker://homeassistant/home-assistant:0.97.2
#       - run: |
#           cd /usr/src/app
#           hassio ha check --config $GITHUB_WORKSPACE

#     steps:
#     - uses: actions/checkout@master
#     - name: Run a one-line script
#       run: echo Hello, world!
#     - name: Run a multi-line script
#       run: |
#         echo Add other actions to build,
#         echo test, and deploy your project.
